const fs = require('fs');

let content = fs.readFileSync('src/customFields.js', 'utf8');

// 1. UPDATE VIEW MODE (lines 22-26 approx)
const oldViewMode = `                    } else {\n                        html += \`<a href="\${url}" target="_blank" class="flex items-center gap-1 text-xs text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/30 px-2 py-1 rounded border border-blue-200 dark:border-blue-800 hover:bg-blue-100 transition-colors">\n                                    <span class="material-symbols-outlined text-[14px]">description</span> <span class="truncate max-w-[150px]">\${name}</span>\n                                 </a>\`;\n                    }`;

const newViewMode = `                    } else {\n                        const title = file.title || name;\n                        const author = file.uploadedBy || 'Usuário Local';\n                        const dateStr = file.uploadedAt ? new Date(file.uploadedAt).toLocaleString('pt-BR') : 'Data desconhecida';\n                        html += \`\n                            <div class="flex flex-col gap-1 text-xs text-slate-700 dark:text-slate-300 bg-slate-50 dark:bg-slate-800/50 p-3 rounded-lg border border-slate-200 dark:border-slate-700 w-full sm:w-[300px]">\n                                <div class="font-semibold text-sm truncate" title="\${title}">\${title}</div>\n                                <div class="flex items-center gap-1 text-slate-500">\n                                    <span class="material-symbols-outlined text-[12px]">person</span> \${author}\n                                </div>\n                                <div class="flex items-center gap-1 text-slate-500">\n                                    <span class="material-symbols-outlined text-[12px]">calendar_today</span> \${dateStr}\n                                </div>\n                                <a href="\${url}" target="_blank" class="mt-2 text-center text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/30 px-2 py-1.5 rounded border border-blue-200 dark:border-blue-800 hover:bg-blue-100 dark:hover:bg-blue-900 transition-colors flex items-center justify-center gap-1 font-medium">\n                                    <span class="material-symbols-outlined text-[16px]">visibility</span> Visualizar\n                                </a>\n                            </div>\`;\n                    }`;

content = content.replace(oldViewMode, newViewMode);

// 2. UPDATE EDIT MODE
const oldEditMode = `                        } else {\n                            return \`<div class="flex items-center gap-1 text-xs text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/30 px-2 py-1 rounded border border-blue-200 dark:border-blue-800" data-url="\${url}">\n                                        <span class="material-symbols-outlined text-[14px]">description</span> \n                                        <span class="truncate max-w-[100px]">\${name}</span>\n                                        <button type="button" onclick="removeFile('\${f.id}', '\${url}')" class="ml-1 text-red-500 hover:text-red-700"><span class="material-symbols-outlined text-[14px]">close</span></button>\n                                    </div>\`;\n                        }`;

const newEditMode = `                        } else {\n                            const title = file.title || name;\n                            const author = file.uploadedBy || 'Usuário Local';\n                            const dateStr = file.uploadedAt ? new Date(file.uploadedAt).toLocaleString('pt-BR') : 'Agora';\n                            return \`\n                            <div class="flex flex-col gap-2 text-xs text-slate-700 dark:text-slate-300 bg-white dark:bg-slate-800 p-3 rounded-lg border border-slate-200 dark:border-slate-700 w-full sm:w-[320px] shadow-sm" data-url="\${url}">\n                                <div>\n                                    <label class="block text-[10px] font-bold text-slate-500 uppercase mb-1">Título do Documento</label>\n                                    <input type="text" value="\${title}" onchange="updateFileTitle('\${f.id}', '\${url}', this.value)" class="w-full px-2 py-1.5 border border-slate-300 dark:border-slate-600 bg-slate-50 dark:bg-slate-900 rounded text-sm focus:outline-none focus:ring-1 focus:ring-primary">\n                                </div>\n                                <div class="grid grid-cols-2 gap-2 mt-1">\n                                    <div class="flex items-center gap-1 text-slate-500 truncate" title="\${author}">\n                                        <span class="material-symbols-outlined text-[12px]">person</span> \${author}\n                                    </div>\n                                    <div class="flex items-center gap-1 text-slate-500 truncate">\n                                        <span class="material-symbols-outlined text-[12px]">calendar_today</span> \${dateStr}\n                                    </div>\n                                </div>\n                                <div class="flex items-center justify-between mt-2 gap-2">\n                                    <a href="\${url}" target="_blank" class="flex-1 text-center text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/30 px-2 py-1 rounded border border-blue-200 dark:border-blue-800 hover:bg-blue-100 transition-colors font-medium flex items-center justify-center gap-1">\n                                        <span class="material-symbols-outlined text-[14px]">visibility</span> Abrir\n                                    </a>\n                                    <button type="button" onclick="removeFile('\${f.id}', '\${url}')" class="flex-1 text-center text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/30 px-2 py-1 rounded border border-red-200 dark:border-red-800 hover:bg-red-100 transition-colors font-medium flex items-center justify-center gap-1">\n                                        <span class="material-symbols-outlined text-[14px]">delete</span> Excluir\n                                    </button>\n                                </div>\n                            </div>\`;\n                        }`;

content = content.replace(oldEditMode, newEditMode);

// 3. UPDATE handleSupabaseUpload
const oldPush = `        files.push({ name: file.name, url: publicUrl, path: filePath });`;
const newPush = `        files.push({ \n            name: file.name, \n            title: file.name, \n            url: publicUrl, \n            path: filePath, \n            uploadedBy: 'Usuário (Você)',\n            uploadedAt: new Date().toISOString()\n        });`;

content = content.replace(oldPush, newPush);

// 4. UPDATE handleSupabaseUpload HTML preview
const oldPreview = `        } else {\n            previewDiv.innerHTML += \`<div class="flex items-center gap-1 text-xs text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/30 px-2 py-1 rounded border border-blue-200 dark:border-blue-800" data-url="\${publicUrl}">\n                                        <span class="material-symbols-outlined text-[14px]">description</span> \n                                        <span class="truncate max-w-[100px]">\${file.name}</span>\n                                        <button type="button" onclick="removeFile('\${fieldId}', '\${publicUrl}')" class="ml-1 text-red-500 hover:text-red-700"><span class="material-symbols-outlined text-[14px]">close</span></button>\n                                    </div>\`;\n        }`;

const newPreview = `        } else {\n            const dateStr = new Date().toLocaleString('pt-BR');\n            const author = 'Usuário (Você)';\n            previewDiv.innerHTML += \`\n            <div class="flex flex-col gap-2 text-xs text-slate-700 dark:text-slate-300 bg-white dark:bg-slate-800 p-3 rounded-lg border border-slate-200 dark:border-slate-700 w-full sm:w-[320px] shadow-sm" data-url="\${publicUrl}">\n                <div>\n                    <label class="block text-[10px] font-bold text-slate-500 uppercase mb-1">Título do Documento</label>\n                    <input type="text" value="\${file.name}" onchange="updateFileTitle('\${fieldId}', '\${publicUrl}', this.value)" class="w-full px-2 py-1.5 border border-slate-300 dark:border-slate-600 bg-slate-50 dark:bg-slate-900 rounded text-sm focus:outline-none focus:ring-1 focus:ring-primary">\n                </div>\n                <div class="grid grid-cols-2 gap-2 mt-1">\n                    <div class="flex items-center gap-1 text-slate-500 truncate" title="\${author}">\n                        <span class="material-symbols-outlined text-[12px]">person</span> \${author}\n                    </div>\n                    <div class="flex items-center gap-1 text-slate-500 truncate">\n                        <span class="material-symbols-outlined text-[12px]">calendar_today</span> \${dateStr}\n                    </div>\n                </div>\n                <div class="flex items-center justify-between mt-2 gap-2">\n                    <a href="\${publicUrl}" target="_blank" class="flex-1 text-center text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/30 px-2 py-1 rounded border border-blue-200 dark:border-blue-800 hover:bg-blue-100 transition-colors font-medium flex items-center justify-center gap-1">\n                        <span class="material-symbols-outlined text-[14px]">visibility</span> Abrir\n                    </a>\n                    <button type="button" onclick="removeFile('\${fieldId}', '\${publicUrl}')" class="flex-1 text-center text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/30 px-2 py-1 rounded border border-red-200 dark:border-red-800 hover:bg-red-100 transition-colors font-medium flex items-center justify-center gap-1">\n                        <span class="material-symbols-outlined text-[14px]">delete</span> Excluir\n                    </button>\n                </div>\n            </div>\`;\n        }`;

content = content.replace(oldPreview, newPreview);

// 5. Add updateFileTitle function at the end
if (!content.includes('function updateFileTitle')) {
    content += `\n\n// === ATUALIZAR TÍTULO DE ARQUIVO ===\nwindow.updateFileTitle = function(fieldId, url, newTitle) {\n    const hiddenInput = document.querySelector(\`input[data-key="\${fieldId}"]\`);\n    if (!hiddenInput) return;\n    \n    try {\n        let files = JSON.parse(hiddenInput.value);\n        let updated = false;\n        files = files.map(f => {\n            if (f.url === url || f === url) {\n                updated = true;\n                if (typeof f === 'string') {\n                    return { name: 'Arquivo', title: newTitle, url: f };\n                } else {\n                    f.title = newTitle;\n                    return f;\n                }\n            }\n            return f;\n        });\n        if (updated) {\n            hiddenInput.value = JSON.stringify(files);\n            console.log('Título do arquivo atualizado para:', newTitle);\n        }\n    } catch(e) {\n        console.error('Erro ao atualizar título do arquivo:', e);\n    }\n};\n`;
}

fs.writeFileSync('src/customFields.js', content, 'utf8');
console.log('customFields.js updated successfully!');
